tinymce.addI18n('tr_TR',{
"Redo": "İrəli",
"Undo": "Geri",
"Cut": "Kəs",
"Copy": "Kopyala",
"Paste": "Yapışdır",
"Select all": "Hamısını seç",
"New document": "Yeni səhifə",
"Ok": "Tamam",
"Cancel": "İmtina",
"Visual aids": "GÖrsel araçlar",
"Bold": "Qalın",
"Italic": "İtalik",
"Underline": "Altı xətli",
"Strikethrough": "Ortası xətli",
"Superscript": "Üst simvol",
"Subscript": "Alt simvol",
"Clear formatting": "Formatı temizlə",
"Align left": "Sola nizamla",
"Align center": "Ortala",
"Align right": "Sağa nizamla",
"Justify": "Hər iki tərəfi nizamlı",
"Bullet list": "Nöqtəli siyahı",
"Numbered list": "Nömrəli siyahı",
"Decrease indent": "Girintini azalt",
"Increase indent": "Girintni artır",
"Close": "Bağla",
"Formats": "Formatlar",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead.": "Tarayıcınız panoya direk erişimi destəlavə etmiyor. Lütfen Ctrl+X\/C\/V klavye Qısa yollarını kullanın.",
"Headers": "Başlıqlar",
"Header 1": "Başlıq 1",
"Header 2": "Başlıq 2",
"Header 3": "Başlıq 3",
"Header 4": "Başlıq 4",
"Header 5": "Başlıq 5",
"Header 6": "Başlıq 6",
"Headings": "Başlıqlar",
"Heading 1": "Başlıq 1",
"Heading 2": "Başlıq 2",
"Heading 3": "Başlıq 3",
"Heading 4": "Başlıq 4",
"Heading 5": "Başlıq 5",
"Heading 6": "Başlıq 6",
"Preformatted": "Önceden biçimlendirilmiş",
"Div": "Div",
"Pre": "Pre",
"Code": "Kod",
"Paragraph": "Paragraf",
"Blockquote": "Blockquote",
"Inline": "Sətir",
"Blocks": "Bloklar",
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "Düz metin modunda yapıştır. Bu seçeneği kapatana kadar içerikler düz metin olarak yapıştırılır.",
"Fonts": "Şriftlər",
"Font Sizes": "Şrift böyüklüyü",
"Class": "Sinif",
"Browse for an image": "Şəkil seçin",
"OR": "ya da",
"Drop an image here": "Şəkil sürükləyib buraxın",
"Upload": "Yüklə",
"Block": "Blok",
"Align": "Nizamla",
"Default": "Varsayılan",
"Circle": "Çevrə",
"Disc": "Disk",
"Square": "Kare",
"Lower Alpha": "Kiçik ABC",
"Lower Greek": "Kiçik Yunan əlifbası",
"Lower Roman": "Kiçik Roman əlifbası",
"Upper Alpha": "Büyük ABC",
"Upper Roman": "Büyük Roman əlifbası",
"Anchor...": "\u00c7apa...",
"Name": "Ad",
"Id": "Id",
"Id should start with a letter, followed only by letters, numbers, dashes, dots, colons or underscores.": "Id bir harf ile başlamalıdır ve sadece harfleri, rakamları, çizgileri, noktaları, virgülleri veya alt çizgileri içermelidir.",
"You have unsaved changes are you sure you want to navigate away?": "Kaydedilmemiş değişiklikler var, sayfadan ayrılmak istediğinize emin misiniz?",
"Restore last draft": "Son taslağı kurtar",
"Special characters...": "Özel Xarakterler...",
"Source code": "Mənbə kodu",
"Insert\/Edit code sample": "Kod yadda saxla\/redaktə et",
"Language": "Dil",
"Code sample...": "Kod Örneği...",
"Color Picker": "Rəng Seçici",
"R": "R",
"G": "G",
"B": "B",
"Left to right": "Soldan sağa",
"Right to left": "Sağdan sola",
"Emoticons...": "İfadələr...",
"Metadata and Document Properties": "Önbilgi ve Belge Özellikleri",
"Title": "Başlıq",
"Keywords": "Anahtar Sözler",
"Description": "Açıklama",
"Robots": "Robotlar",
"Author": "Yazar",
"Encoding": "Kodlama",
"Fullscreen": "Tam ekran",
"Action": "Eylem",
"Shortcut": "Qısa yol",
"Help": "Yardım",
"Address": "Adres",
"Focus to menubar": "Menü çubuğuna odaklan.",
"Focus to toolbar": "Araç çubuğuna odaklan.",
"Focus to element path": "Eleman yoluna odaklan",
"Focus to contextual toolbar": "Bağlamsal araç çubuğuna odaklan",
"Insert link (if link plugin activated)": "Link əlavə et (Link əlavə etntisi aktif ise)",
"Save (if save plugin activated)": "Kaydet (Kayıt əlavə etntisi aktif ise)",
"Find (if searchreplace plugin activated)": "Axtar (SearchReplace əlavə etntisi aktif ise)",
"Plugins installed ({0}):": "Yüklü əlavə etnti sayısı : ({0}):",
"Premium plugins:": "Premium əlavə etntileri",
"Learn more...": "Daha fazla bilgi edinin.",
"You are using {0}": "{0} kullanıyorsun.",
"Plugins": "əlavə etntiler",
"Handy Shortcuts": "Kullanışlı Qısa yollar",
"Horizontal line": "Yatay çizgi",
"Insert\/edit image": "Şəkil əlavə et\/Redaktə",
"Image description": "Şəkil açıklaması",
"Source": "Kaynak",
"Dimensions": "Boyutlar",
"Constrain proportions": "En - Boy oranını koru",
"General": "Genel",
"Advanced": "Gelişmiş",
"Style": "Stil",
"Vertical space": "Dikey boşluk",
"Horizontal space": "Yatay boşluk",
"Border": "\u00c7erçeve",
"Insert image": "Şəkil yüklə",
"Image...": "Şəkil...",
"Image list": "Şəkil siyahı",
"Rotate counterclockwise": "Saat yÖnünün tersine dÖndür",
"Rotate clockwise": "Saat yÖnünde dÖndür",
"Flip vertically": "Dikey çevir",
"Flip horizontally": "Yatay çevir",
"Edit image": "GÖrüntüyü Redaktə",
"Image options": "GÖrüntü seçenəlavə etri",
"Zoom in": "Yaxınlaşdır",
"Zoom out": "Uzaqlaşdır",
"Crop": "Kes",
"Resize": "Yeniden Boyutlandır",
"Orientation": "YÖnünü Belirle",
"Brightness": "Parlaklık",
"Sharpen": "Keskinleştir",
"Contrast": "Kontrast",
"Color levels": "Renk seviyesi",
"Gamma": "Gama",
"Invert": "Tersine çevir",
"Apply": "Uygula",
"Back": "Geri",
"Insert date\/time": "Tarih \/ Zaman əlavə et",
"Date\/time": "Tarih\/zaman",
"Insert\/Edit Link": "Link əlavə et\/Redaktə",
"Insert\/edit link": "Link əlavə et\/Redaktə",
"Text to display": "GÖrünen yazı",
"Url": "Url",
"Open link in...": "Linki aç...",
"Current window": "Mevcut pencere",
"None": "Hiçbiri",
"New window": "Yeni pencere",
"Remove link": "Linki kaldır",
"Anchors": "\u00c7apalar",
"Link...": "Link...",
"Paste or type a link": "Bir Link yapıştırın yada yazın.",
"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "Girdiğiniz URL bir eposta adresi gibi gÖzüküyor. Gerekli olan mailto: Önekini əlavə etmek ister misiniz?",
"The URL you entered seems to be an external link. Do you want to add the required http:\/\/ prefix?": "Girdiğiniz URL bir dış Link gibi gÖzüküyor. Gerekli olan http:\/\/ Önekini əlavə etmek ister misiniz?",
"Link list": "Link listesi",
"Insert video": "Video əlavə et",
"Insert\/edit video": "Video əlavə et\/Redaktə",
"Insert\/edit media": "Medya əlavə et\/Redaktə",
"Alternative source": "Alternatif kaynak",
"Alternative source URL": "Alternatif kaynak URL",
"Media poster (Image URL)": "Medya posteri (Şəkil URL)",
"Paste your embed code below:": "Medya gÖmme kodunu buraya yapıştır:",
"Embed": "GÖmme",
"Media...": "Medya...",
"Nonbreaking space": "BÖlünemez boşluk",
"Page break": "Sayfa sonu",
"Paste as text": "Metin olarak yapıştır",
"Preview": "Önizleme",
"Print...": "Çap...",
"Save": "Kaydet",
"Find": "Tap",
"Replace with": "Bununla değiştir",
"Replace": "Dəyişdir",
"Replace all": "Tümünü değiştir",
"Previous": "Geri",
"Next": "Sonraki",
"Find and replace...": "Tap və dəyişdir...",
"Could not find the specified string.": "Hər hansı bir nəticə tapılmadı",
"Match case": "Büyük \/ Kiçik hərfə duyarlı",
"Find whole words only": "Sadece sözü axtar",
"Spell check": "Yazım denetimi",
"Ignore": "Yoksay",
"Ignore all": "Tümünü yoksay",
"Finish": "Bitir",
"Add to Dictionary": "Sözlüğe əlavə et",
"Insert table": "Tablo əlavə et",
"Table properties": "Tablo Özellikleri",
"Delete table": "Tabloyu sil",
"Cell": "Hücre",
"Row": "Satır",
"Column": "Sütun",
"Cell properties": "Hücre Özellikleri",
"Merge cells": "Hücreleri birleştir",
"Split cell": "Hücreleri ayır",
"Insert row before": "Öncesine yeni satır əlavə et",
"Insert row after": "Sonrasına yeni satır əlavə et",
"Delete row": "Satırı sil",
"Row properties": "Satır Özellikleri",
"Cut row": "Satırı kes",
"Copy row": "Satırı kopyala",
"Paste row before": "Öncesine satır yapıştır",
"Paste row after": "Sonrasına satır  yapıştır",
"Insert column before": "Öncesine yeni sütun əlavə et",
"Insert column after": "Sonrasına yeni sütun əlavə et",
"Delete column": "Sütunu sil",
"Cols": "Sütunlar",
"Rows": "Satırlar",
"Width": "Genişlik",
"Height": "Yükseklik",
"Cell spacing": "Hücre aralığı",
"Cell padding": "Hücre iç boşluğu",
"Show caption": "Başlığı gÖster",
"Left": "Sol",
"Center": "Orta",
"Right": "Sağ",
"Cell type": "Hücre tipi",
"Scope": "Kapsam",
"Alignment": "Hizalama",
"H Align": "Yatay Hizalama",
"V Align": "Dikey Hizalama",
"Top": "\u00dcst",
"Middle": "Orta",
"Bottom": "Alt",
"Header cell": "Başlıq hücresi",
"Row group": "Satır grubu",
"Column group": "Sütun grubu",
"Row type": "Satır tipi",
"Header": "Başlıq",
"Body": "GÖvde",
"Footer": "Alt",
"Border color": "Kenarlık Rengi",
"Insert template...": "Şablon əlavə et...",
"Templates": "Şablonlar",
"Template": "Tema",
"Text color": "Yazı rengi",
"Background color": "Arkaplan rengi",
"Custom...": "Xüsusi",
"Custom color": "Xüsusi Rəng",
"No color": "Rəng yox",
"Remove color": "Rəngi ləğv et",
"Table of Contents": "İçindəkilər",
"Show blocks": "Blokları gÖrüntüle",
"Show invisible characters": "Görünməz xarakterləri göster",
"Word count": "Söz sayı",
"Words: {0}": "Söz: {0}",
"{0} words": "{0} Söz",
"File": "Fayl",
"Edit": "Redaktə",
"Insert": "Daxil et",
"View": "Görünüş",
"Format": "Biçim",
"Table": "Cədvəl",
"Tools": "Araçlar",
"Powered by {0}": "{0} tarafından yapılmıştır ",
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "Zengin Metin Alanı. Menü için ALT-F9 Qısa yolunu kullanın. Araç çubuğu için ALT-F10 Qısa yolunu kullanın. Yardım için ALT-0 Qısa yolunu kullanın.",
"Image title": "Şəkil başlığı",
"Border width": "Kenar genişliği",
"Border style": "Kenar sitili",
"Error": "Hata",
"Warn": "Uyarı",
"Valid": "Geçerli",
"To open the popup, press Shift+Enter": "Popup'ı açmak için Shift+Enter'a basın",
"Rich Text Area. Press ALT-0 for help.": "Zengin Metin Alanı. Yardım için Alt-0'a basın.",
"System Font": "Sistem Yazı Tipi",
"Failed to upload image: {0}": "Şəkil yüklenemedi: {0}",
"Failed to load plugin: {0} from url {1}": "əlavə etnti yüklenemedi: {1} url\u2019sinden {0} ",
"Failed to load plugin url: {0}": "Url əlavə etntisi yüklenemedi: {0}",
"Failed to initialize plugin: {0}": "əlavə etnti başlatılamadı: {0}",
"example": "Örnek",
"Search": "Ara",
"All": "Tümü",
"Currency": "Para birimi",
"Text": "Metin",
"Quotations": "Alıntı",
"Mathematical": "Matematik",
"Extended Latin": "Uzatılmış Latin",
"Symbols": "Semboller",
"Arrows": "Oklar",
"User Defined": "Kullanıcı Tanımlı",
"dollar sign": "dolar işarəsi",
"currency sign": "para birimi işarəsi",
"euro-currency sign": "euro para birimi işarəsi",
"colon sign": "colon işarəsi",
"cruzeiro sign": "cruzeiro işarəsi",
"french franc sign": "fransız frangı işarəsi",
"lira sign": "lira işarəsi",
"mill sign": "mill işarəsi",
"naira sign": "naira işarəsi",
"peseta sign": "peseta işarəsi",
"rupee sign": "rupi işarəsi",
"won sign": "won işarəsi",
"new sheqel sign": "yeni şekel işarəsi",
"dong sign": "dong işarəsi",
"kip sign": "kip işarəsi",
"tugrik sign": "tugrik işarəsi",
"drachma sign": "drahma işarəsi",
"german penny symbol": "alman kuruş sembolü",
"peso sign": "peso işarəsi",
"guarani sign": "guarani işarəsi",
"austral sign": "austral işarəsi",
"hryvnia sign": "hrivniya işarəsi",
"cedi sign": "cedi işarəsi",
"livre tournois sign": "livre tournois işarəsi",
"spesmilo sign": "spesmilo işarəsi",
"tenge sign": "tenge işarəsi",
"indian rupee sign": "hindistan rupisi işarəsi",
"turkish lira sign": "türk lirası işarəsi",
"nordic mark sign": "nordic işarəsi",
"manat sign": "manat işarəsi",
"ruble sign": "ruble işarəsi",
"yen character": "yen Xarakteri",
"yuan character": "yuan Xarakteri",
"yuan character, in hong kong and taiwan": "yuan Xarakteri, hong kong ve tayvan'da kullanılan",
"yen\/yuan character variant one": "yen\/yuan Xarakter değişkeni",
"Loading emoticons...": "İfadələr yüklənir...",
"Could not load emoticons": "İfadeler yüklenemedi",
"People": "İnsan",
"Animals and Nature": "Hayvanlar ve Doğa",
"Food and Drink": "Yiyecek ve İçecek",
"Activity": "Etkinlik",
"Travel and Places": "Gezi ve Yerler",
"Objects": "Nesneler",
"Flags": "Bayraklar",
"Characters": "Xarakter",
"Characters (no spaces)": "Xarakter (boşluksuz)",
"Error: Form submit field collision.": "Hata: Form gÖnderme alanı çatışması.",
"Error: No form element found.": "Hata: Form elemanı bulunamadı.",
"Update": "Güncelleştir",
"Color swatch": "Renk Örneği",
"Turquoise": "Turkuaz",
"Green": "Yeşil",
"Blue": "Mavi",
"Purple": "Mor",
"Navy Blue": "Lacivert",
"Dark Turquoise": "Koyu Turkuaz",
"Dark Green": "Koyu Yeşil",
"Medium Blue": "Donuk Mavi",
"Medium Purple": "Orta Mor",
"Midnight Blue": "Gece Yarısı Mavisi",
"Yellow": "Sarı",
"Orange": "Turuncu",
"Red": "Kırmızı",
"Light Gray": "Açık Gri",
"Gray": "Gri",
"Dark Yellow": "Koyu Sarı",
"Dark Orange": "Koyu Turuncu",
"Dark Red": "Koyu Kırmızı",
"Medium Gray": "Orta Gri",
"Dark Gray": "Koyu Gri",
"Black": "Siyah",
"White": "Beyaz",
"Switch to or from fullscreen mode": "Tam ekran moduna geç veya çık",
"Open help dialog": "Yardım penceresini aç",
"history": "geçmiş",
"styles": "stiller",
"formatting": "biçimlendirme",
"alignment": "hizalanma",
"indentation": "girinti",
"permanent pen": "kalıcı kalem",
"comments": "yorumlar",
"Anchor": "\u00c7apa",
"Special character": "Özel Xarakter",
"Code sample": "Kod Örneği",
"Color": "Rəng",
"Emoticons": "Gülücükler",
"Document properties": "Doküman Özellikleri",
"Image": "Şəkil",
"Insert link": "Link daxil et",
"Target": "Hedef",
"Link": "Link",
"Poster": "Poster",
"Media": "Medya",
"Print": "Çap",
"Prev": "Əvvəlki",
"Find and replace": "Axtar və dəyişdir",
"Whole words": "Tam sÖzcükler",
"Spellcheck": "Yazım denetimi",
"Caption": "Başlıq",
"Insert template": "Şablon əlavə et"
});
